<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_usage.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.ApiUsageItem</code>
 */
class ApiUsageItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string product = 1;</code>
     */
    protected $product = '';
    /**
     * Generated from protobuf field <code>.finazon.ApiCalls apiCalls = 2;</code>
     */
    protected $apiCalls = null;
    /**
     * Generated from protobuf field <code>.finazon.ApiCalls historicalApiCalls = 3;</code>
     */
    protected $historicalApiCalls = null;
    /**
     * Generated from protobuf field <code>.finazon.ApiCalls referenceApiCalls = 4;</code>
     */
    protected $referenceApiCalls = null;
    /**
     * Generated from protobuf field <code>.finazon.ApiCalls timeSeriesApiCalls = 5;</code>
     */
    protected $timeSeriesApiCalls = null;
    /**
     * Generated from protobuf field <code>.finazon.ApiCalls snapshotsApiCalls = 6;</code>
     */
    protected $snapshotsApiCalls = null;
    /**
     * Generated from protobuf field <code>.finazon.ApiCalls tradesApiCalls = 7;</code>
     */
    protected $tradesApiCalls = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $product
     *     @type \Finazon\Grpc\Api\ApiCalls $apiCalls
     *     @type \Finazon\Grpc\Api\ApiCalls $historicalApiCalls
     *     @type \Finazon\Grpc\Api\ApiCalls $referenceApiCalls
     *     @type \Finazon\Grpc\Api\ApiCalls $timeSeriesApiCalls
     *     @type \Finazon\Grpc\Api\ApiCalls $snapshotsApiCalls
     *     @type \Finazon\Grpc\Api\ApiCalls $tradesApiCalls
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\ApiUsage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string product = 1;</code>
     * @return string
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Generated from protobuf field <code>string product = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProduct($var)
    {
        GPBUtil::checkString($var, True);
        $this->product = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls apiCalls = 2;</code>
     * @return \Finazon\Grpc\Api\ApiCalls
     */
    public function getApiCalls()
    {
        return $this->apiCalls;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls apiCalls = 2;</code>
     * @param \Finazon\Grpc\Api\ApiCalls $var
     * @return $this
     */
    public function setApiCalls($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\ApiCalls::class);
        $this->apiCalls = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls historicalApiCalls = 3;</code>
     * @return \Finazon\Grpc\Api\ApiCalls
     */
    public function getHistoricalApiCalls()
    {
        return $this->historicalApiCalls;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls historicalApiCalls = 3;</code>
     * @param \Finazon\Grpc\Api\ApiCalls $var
     * @return $this
     */
    public function setHistoricalApiCalls($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\ApiCalls::class);
        $this->historicalApiCalls = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls referenceApiCalls = 4;</code>
     * @return \Finazon\Grpc\Api\ApiCalls
     */
    public function getReferenceApiCalls()
    {
        return $this->referenceApiCalls;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls referenceApiCalls = 4;</code>
     * @param \Finazon\Grpc\Api\ApiCalls $var
     * @return $this
     */
    public function setReferenceApiCalls($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\ApiCalls::class);
        $this->referenceApiCalls = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls timeSeriesApiCalls = 5;</code>
     * @return \Finazon\Grpc\Api\ApiCalls
     */
    public function getTimeSeriesApiCalls()
    {
        return $this->timeSeriesApiCalls;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls timeSeriesApiCalls = 5;</code>
     * @param \Finazon\Grpc\Api\ApiCalls $var
     * @return $this
     */
    public function setTimeSeriesApiCalls($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\ApiCalls::class);
        $this->timeSeriesApiCalls = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls snapshotsApiCalls = 6;</code>
     * @return \Finazon\Grpc\Api\ApiCalls
     */
    public function getSnapshotsApiCalls()
    {
        return $this->snapshotsApiCalls;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls snapshotsApiCalls = 6;</code>
     * @param \Finazon\Grpc\Api\ApiCalls $var
     * @return $this
     */
    public function setSnapshotsApiCalls($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\ApiCalls::class);
        $this->snapshotsApiCalls = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls tradesApiCalls = 7;</code>
     * @return \Finazon\Grpc\Api\ApiCalls
     */
    public function getTradesApiCalls()
    {
        return $this->tradesApiCalls;
    }

    /**
     * Generated from protobuf field <code>.finazon.ApiCalls tradesApiCalls = 7;</code>
     * @param \Finazon\Grpc\Api\ApiCalls $var
     * @return $this
     */
    public function setTradesApiCalls($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\ApiCalls::class);
        $this->tradesApiCalls = $var;

        return $this;
    }

}

