<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binance.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.BinanceTimeSeries</code>
 */
class BinanceTimeSeries extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>double open = 2;</code>
     */
    protected $open = 0.0;
    /**
     * Generated from protobuf field <code>double close = 3;</code>
     */
    protected $close = 0.0;
    /**
     * Generated from protobuf field <code>double high = 4;</code>
     */
    protected $high = 0.0;
    /**
     * Generated from protobuf field <code>double low = 5;</code>
     */
    protected $low = 0.0;
    /**
     * Generated from protobuf field <code>double trades = 6;</code>
     */
    protected $trades = 0.0;
    /**
     * Generated from protobuf field <code>double base_volume = 7;</code>
     */
    protected $base_volume = 0.0;
    /**
     * Generated from protobuf field <code>double quote_volume = 8;</code>
     */
    protected $quote_volume = 0.0;
    /**
     * Generated from protobuf field <code>double taker_buy_base_asset_volume = 9;</code>
     */
    protected $taker_buy_base_asset_volume = 0.0;
    /**
     * Generated from protobuf field <code>double taker_buy_quote_asset_volume = 10;</code>
     */
    protected $taker_buy_quote_asset_volume = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *     @type float $open
     *     @type float $close
     *     @type float $high
     *     @type float $low
     *     @type float $trades
     *     @type float $base_volume
     *     @type float $quote_volume
     *     @type float $taker_buy_base_asset_volume
     *     @type float $taker_buy_quote_asset_volume
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Binance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double open = 2;</code>
     * @return float
     */
    public function getOpen()
    {
        return $this->open;
    }

    /**
     * Generated from protobuf field <code>double open = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setOpen($var)
    {
        GPBUtil::checkDouble($var);
        $this->open = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double close = 3;</code>
     * @return float
     */
    public function getClose()
    {
        return $this->close;
    }

    /**
     * Generated from protobuf field <code>double close = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setClose($var)
    {
        GPBUtil::checkDouble($var);
        $this->close = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double high = 4;</code>
     * @return float
     */
    public function getHigh()
    {
        return $this->high;
    }

    /**
     * Generated from protobuf field <code>double high = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setHigh($var)
    {
        GPBUtil::checkDouble($var);
        $this->high = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double low = 5;</code>
     * @return float
     */
    public function getLow()
    {
        return $this->low;
    }

    /**
     * Generated from protobuf field <code>double low = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setLow($var)
    {
        GPBUtil::checkDouble($var);
        $this->low = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double trades = 6;</code>
     * @return float
     */
    public function getTrades()
    {
        return $this->trades;
    }

    /**
     * Generated from protobuf field <code>double trades = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setTrades($var)
    {
        GPBUtil::checkDouble($var);
        $this->trades = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double base_volume = 7;</code>
     * @return float
     */
    public function getBaseVolume()
    {
        return $this->base_volume;
    }

    /**
     * Generated from protobuf field <code>double base_volume = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseVolume($var)
    {
        GPBUtil::checkDouble($var);
        $this->base_volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double quote_volume = 8;</code>
     * @return float
     */
    public function getQuoteVolume()
    {
        return $this->quote_volume;
    }

    /**
     * Generated from protobuf field <code>double quote_volume = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setQuoteVolume($var)
    {
        GPBUtil::checkDouble($var);
        $this->quote_volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double taker_buy_base_asset_volume = 9;</code>
     * @return float
     */
    public function getTakerBuyBaseAssetVolume()
    {
        return $this->taker_buy_base_asset_volume;
    }

    /**
     * Generated from protobuf field <code>double taker_buy_base_asset_volume = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setTakerBuyBaseAssetVolume($var)
    {
        GPBUtil::checkDouble($var);
        $this->taker_buy_base_asset_volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double taker_buy_quote_asset_volume = 10;</code>
     * @return float
     */
    public function getTakerBuyQuoteAssetVolume()
    {
        return $this->taker_buy_quote_asset_volume;
    }

    /**
     * Generated from protobuf field <code>double taker_buy_quote_asset_volume = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setTakerBuyQuoteAssetVolume($var)
    {
        GPBUtil::checkDouble($var);
        $this->taker_buy_quote_asset_volume = $var;

        return $this;
    }

}

