<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: benzinga.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.DividentsCalendarItem</code>
 */
class DividentsCalendarItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string record_id = 1;</code>
     */
    protected $record_id = '';
    /**
     * Generated from protobuf field <code>string ticker = 2;</code>
     */
    protected $ticker = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     */
    protected $mic = '';
    /**
     * Generated from protobuf field <code>string currency = 5;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>string ex_dividend_date = 6;</code>
     */
    protected $ex_dividend_date = '';
    /**
     * Generated from protobuf field <code>string dividend_type = 7;</code>
     */
    protected $dividend_type = '';
    /**
     * Generated from protobuf field <code>double dividend = 8;</code>
     */
    protected $dividend = 0.0;
    /**
     * Generated from protobuf field <code>double dividend_yield = 9;</code>
     */
    protected $dividend_yield = 0.0;
    /**
     * Generated from protobuf field <code>string dividend_prior = 10;</code>
     */
    protected $dividend_prior = '';
    /**
     * Generated from protobuf field <code>string declaration_date = 11;</code>
     */
    protected $declaration_date = '';
    /**
     * Generated from protobuf field <code>string payable_date = 12;</code>
     */
    protected $payable_date = '';
    /**
     * Generated from protobuf field <code>string record_date = 13;</code>
     */
    protected $record_date = '';
    /**
     * Generated from protobuf field <code>bool end_regular_dividend = 14;</code>
     */
    protected $end_regular_dividend = false;
    /**
     * Generated from protobuf field <code>int32 frequency = 15;</code>
     */
    protected $frequency = 0;
    /**
     * Generated from protobuf field <code>int32 importance = 16;</code>
     */
    protected $importance = 0;
    /**
     * Generated from protobuf field <code>string notes = 17;</code>
     */
    protected $notes = '';
    /**
     * Generated from protobuf field <code>int64 updated = 18;</code>
     */
    protected $updated = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $record_id
     *     @type string $ticker
     *     @type string $name
     *     @type string $mic
     *     @type string $currency
     *     @type string $ex_dividend_date
     *     @type string $dividend_type
     *     @type float $dividend
     *     @type float $dividend_yield
     *     @type string $dividend_prior
     *     @type string $declaration_date
     *     @type string $payable_date
     *     @type string $record_date
     *     @type bool $end_regular_dividend
     *     @type int $frequency
     *     @type int $importance
     *     @type string $notes
     *     @type int|string $updated
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Benzinga::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string record_id = 1;</code>
     * @return string
     */
    public function getRecordId()
    {
        return $this->record_id;
    }

    /**
     * Generated from protobuf field <code>string record_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRecordId($var)
    {
        GPBUtil::checkString($var, True);
        $this->record_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ticker = 2;</code>
     * @return string
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     * Generated from protobuf field <code>string ticker = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTicker($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     * @return string
     */
    public function getMic()
    {
        return $this->mic;
    }

    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMic($var)
    {
        GPBUtil::checkString($var, True);
        $this->mic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 5;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ex_dividend_date = 6;</code>
     * @return string
     */
    public function getExDividendDate()
    {
        return $this->ex_dividend_date;
    }

    /**
     * Generated from protobuf field <code>string ex_dividend_date = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setExDividendDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->ex_dividend_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dividend_type = 7;</code>
     * @return string
     */
    public function getDividendType()
    {
        return $this->dividend_type;
    }

    /**
     * Generated from protobuf field <code>string dividend_type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDividendType($var)
    {
        GPBUtil::checkString($var, True);
        $this->dividend_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double dividend = 8;</code>
     * @return float
     */
    public function getDividend()
    {
        return $this->dividend;
    }

    /**
     * Generated from protobuf field <code>double dividend = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setDividend($var)
    {
        GPBUtil::checkDouble($var);
        $this->dividend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double dividend_yield = 9;</code>
     * @return float
     */
    public function getDividendYield()
    {
        return $this->dividend_yield;
    }

    /**
     * Generated from protobuf field <code>double dividend_yield = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setDividendYield($var)
    {
        GPBUtil::checkDouble($var);
        $this->dividend_yield = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dividend_prior = 10;</code>
     * @return string
     */
    public function getDividendPrior()
    {
        return $this->dividend_prior;
    }

    /**
     * Generated from protobuf field <code>string dividend_prior = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDividendPrior($var)
    {
        GPBUtil::checkString($var, True);
        $this->dividend_prior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string declaration_date = 11;</code>
     * @return string
     */
    public function getDeclarationDate()
    {
        return $this->declaration_date;
    }

    /**
     * Generated from protobuf field <code>string declaration_date = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setDeclarationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->declaration_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payable_date = 12;</code>
     * @return string
     */
    public function getPayableDate()
    {
        return $this->payable_date;
    }

    /**
     * Generated from protobuf field <code>string payable_date = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setPayableDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->payable_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string record_date = 13;</code>
     * @return string
     */
    public function getRecordDate()
    {
        return $this->record_date;
    }

    /**
     * Generated from protobuf field <code>string record_date = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setRecordDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->record_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool end_regular_dividend = 14;</code>
     * @return bool
     */
    public function getEndRegularDividend()
    {
        return $this->end_regular_dividend;
    }

    /**
     * Generated from protobuf field <code>bool end_regular_dividend = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setEndRegularDividend($var)
    {
        GPBUtil::checkBool($var);
        $this->end_regular_dividend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 frequency = 15;</code>
     * @return int
     */
    public function getFrequency()
    {
        return $this->frequency;
    }

    /**
     * Generated from protobuf field <code>int32 frequency = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setFrequency($var)
    {
        GPBUtil::checkInt32($var);
        $this->frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 importance = 16;</code>
     * @return int
     */
    public function getImportance()
    {
        return $this->importance;
    }

    /**
     * Generated from protobuf field <code>int32 importance = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setImportance($var)
    {
        GPBUtil::checkInt32($var);
        $this->importance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 17;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated = 18;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Generated from protobuf field <code>int64 updated = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

}

