<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: benzinga.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\EarningsCalendarItem\Revenue instead.
     * @deprecated
     */
    class EarningsCalendarItem_Revenue {}
}
class_exists(EarningsCalendarItem\Revenue::class);
@trigger_error('Finazon\Grpc\Api\EarningsCalendarItem_Revenue is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\EarningsCalendarItem\Revenue instead', E_USER_DEPRECATED);

