<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: benzinga.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\EarningsCalendarItem\Eps instead.
     * @deprecated
     */
    class EarningsCalendarItem_Eps {}
}
class_exists(EarningsCalendarItem\Eps::class);
@trigger_error('Finazon\Grpc\Api\EarningsCalendarItem_Eps is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\EarningsCalendarItem\Eps instead', E_USER_DEPRECATED);

