<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: benzinga.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.EarningsCalendarItem</code>
 */
class EarningsCalendarItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string currency = 1;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>string date = 2;</code>
     */
    protected $date = '';
    /**
     * Generated from protobuf field <code>bool date_confirmed = 3;</code>
     */
    protected $date_confirmed = false;
    /**
     * Generated from protobuf field <code>.finazon.EarningsCalendarItem.Eps eps = 4;</code>
     */
    protected $eps = null;
    /**
     * Generated from protobuf field <code>int32 importance = 5;</code>
     */
    protected $importance = 0;
    /**
     * Generated from protobuf field <code>string mic = 6;</code>
     */
    protected $mic = '';
    /**
     * Generated from protobuf field <code>string name = 7;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string notes = 8;</code>
     */
    protected $notes = '';
    /**
     * Generated from protobuf field <code>string period = 9;</code>
     */
    protected $period = '';
    /**
     * Generated from protobuf field <code>int32 period_year = 10;</code>
     */
    protected $period_year = 0;
    /**
     * Generated from protobuf field <code>string record_id = 11;</code>
     */
    protected $record_id = '';
    /**
     * Generated from protobuf field <code>.finazon.EarningsCalendarItem.Revenue revenue = 12;</code>
     */
    protected $revenue = null;
    /**
     * Generated from protobuf field <code>string ticker = 13;</code>
     */
    protected $ticker = '';
    /**
     * Generated from protobuf field <code>string time = 14;</code>
     */
    protected $time = '';
    /**
     * Generated from protobuf field <code>int64 updated = 15;</code>
     */
    protected $updated = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $currency
     *     @type string $date
     *     @type bool $date_confirmed
     *     @type \Finazon\Grpc\Api\EarningsCalendarItem\Eps $eps
     *     @type int $importance
     *     @type string $mic
     *     @type string $name
     *     @type string $notes
     *     @type string $period
     *     @type int $period_year
     *     @type string $record_id
     *     @type \Finazon\Grpc\Api\EarningsCalendarItem\Revenue $revenue
     *     @type string $ticker
     *     @type string $time
     *     @type int|string $updated
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Benzinga::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string currency = 1;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date = 2;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Generated from protobuf field <code>string date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool date_confirmed = 3;</code>
     * @return bool
     */
    public function getDateConfirmed()
    {
        return $this->date_confirmed;
    }

    /**
     * Generated from protobuf field <code>bool date_confirmed = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDateConfirmed($var)
    {
        GPBUtil::checkBool($var);
        $this->date_confirmed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.EarningsCalendarItem.Eps eps = 4;</code>
     * @return \Finazon\Grpc\Api\EarningsCalendarItem\Eps
     */
    public function getEps()
    {
        return $this->eps;
    }

    /**
     * Generated from protobuf field <code>.finazon.EarningsCalendarItem.Eps eps = 4;</code>
     * @param \Finazon\Grpc\Api\EarningsCalendarItem\Eps $var
     * @return $this
     */
    public function setEps($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\EarningsCalendarItem_Eps::class);
        $this->eps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 importance = 5;</code>
     * @return int
     */
    public function getImportance()
    {
        return $this->importance;
    }

    /**
     * Generated from protobuf field <code>int32 importance = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setImportance($var)
    {
        GPBUtil::checkInt32($var);
        $this->importance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mic = 6;</code>
     * @return string
     */
    public function getMic()
    {
        return $this->mic;
    }

    /**
     * Generated from protobuf field <code>string mic = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMic($var)
    {
        GPBUtil::checkString($var, True);
        $this->mic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 7;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 8;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string period = 9;</code>
     * @return string
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * Generated from protobuf field <code>string period = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkString($var, True);
        $this->period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 period_year = 10;</code>
     * @return int
     */
    public function getPeriodYear()
    {
        return $this->period_year;
    }

    /**
     * Generated from protobuf field <code>int32 period_year = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPeriodYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->period_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string record_id = 11;</code>
     * @return string
     */
    public function getRecordId()
    {
        return $this->record_id;
    }

    /**
     * Generated from protobuf field <code>string record_id = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setRecordId($var)
    {
        GPBUtil::checkString($var, True);
        $this->record_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.EarningsCalendarItem.Revenue revenue = 12;</code>
     * @return \Finazon\Grpc\Api\EarningsCalendarItem\Revenue
     */
    public function getRevenue()
    {
        return $this->revenue;
    }

    /**
     * Generated from protobuf field <code>.finazon.EarningsCalendarItem.Revenue revenue = 12;</code>
     * @param \Finazon\Grpc\Api\EarningsCalendarItem\Revenue $var
     * @return $this
     */
    public function setRevenue($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\EarningsCalendarItem_Revenue::class);
        $this->revenue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ticker = 13;</code>
     * @return string
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     * Generated from protobuf field <code>string ticker = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setTicker($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time = 14;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>string time = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated = 15;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Generated from protobuf field <code>int64 updated = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

}

