<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_usage.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetApiUsageRequest</code>
 */
class GetApiUsageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string product = 1;</code>
     */
    protected $product = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $product
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\ApiUsage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string product = 1;</code>
     * @return string
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Generated from protobuf field <code>string product = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProduct($var)
    {
        GPBUtil::checkString($var, True);
        $this->product = $var;

        return $this;
    }

}

