<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypto.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetCryptoTimeSeriesRequest</code>
 */
class GetCryptoTimeSeriesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     */
    protected $ticker = '';
    /**
     * Generated from protobuf field <code>string interval = 3;</code>
     */
    protected $interval = '';
    /**
     * Generated from protobuf field <code>int64 start_at = 5;</code>
     */
    protected $start_at = 0;
    /**
     * Generated from protobuf field <code>int64 end_at = 6;</code>
     */
    protected $end_at = 0;
    /**
     * Generated from protobuf field <code>int32 page = 7;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int32 page_size = 8;</code>
     */
    protected $page_size = 0;
    /**
     * Generated from protobuf field <code>string order = 9;</code>
     */
    protected $order = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ticker
     *     @type string $interval
     *     @type int|string $start_at
     *     @type int|string $end_at
     *     @type int $page
     *     @type int $page_size
     *     @type string $order
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Crypto::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     * @return string
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTicker($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string interval = 3;</code>
     * @return string
     */
    public function getInterval()
    {
        return $this->interval;
    }

    /**
     * Generated from protobuf field <code>string interval = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInterval($var)
    {
        GPBUtil::checkString($var, True);
        $this->interval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_at = 5;</code>
     * @return int|string
     */
    public function getStartAt()
    {
        return $this->start_at;
    }

    /**
     * Generated from protobuf field <code>int64 start_at = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end_at = 6;</code>
     * @return int|string
     */
    public function getEndAt()
    {
        return $this->end_at;
    }

    /**
     * Generated from protobuf field <code>int64 end_at = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 7;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 8;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order = 9;</code>
     * @return string
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Generated from protobuf field <code>string order = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkString($var, True);
        $this->order = $var;

        return $this;
    }

}

