<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetSnapshotResponse</code>
 */
class GetSnapshotResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv last_day = 1;</code>
     */
    protected $last_day = null;
    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv last_month = 2;</code>
     */
    protected $last_month = null;
    /**
     * Generated from protobuf field <code>.finazon.SnapshotLastTrade last_trade = 3;</code>
     */
    protected $last_trade = null;
    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv previous_day = 4;</code>
     */
    protected $previous_day = null;
    /**
     * Generated from protobuf field <code>.finazon.SnapshotLastFiftyTwoWeek last_fifty_two_week = 5;</code>
     */
    protected $last_fifty_two_week = null;
    /**
     * Generated from protobuf field <code>.finazon.SnapshotChange change = 6;</code>
     */
    protected $change = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Finazon\Grpc\Api\SnapshotOhlcv $last_day
     *     @type \Finazon\Grpc\Api\SnapshotOhlcv $last_month
     *     @type \Finazon\Grpc\Api\SnapshotLastTrade $last_trade
     *     @type \Finazon\Grpc\Api\SnapshotOhlcv $previous_day
     *     @type \Finazon\Grpc\Api\SnapshotLastFiftyTwoWeek $last_fifty_two_week
     *     @type \Finazon\Grpc\Api\SnapshotChange $change
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Snapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv last_day = 1;</code>
     * @return \Finazon\Grpc\Api\SnapshotOhlcv
     */
    public function getLastDay()
    {
        return $this->last_day;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv last_day = 1;</code>
     * @param \Finazon\Grpc\Api\SnapshotOhlcv $var
     * @return $this
     */
    public function setLastDay($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\SnapshotOhlcv::class);
        $this->last_day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv last_month = 2;</code>
     * @return \Finazon\Grpc\Api\SnapshotOhlcv
     */
    public function getLastMonth()
    {
        return $this->last_month;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv last_month = 2;</code>
     * @param \Finazon\Grpc\Api\SnapshotOhlcv $var
     * @return $this
     */
    public function setLastMonth($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\SnapshotOhlcv::class);
        $this->last_month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotLastTrade last_trade = 3;</code>
     * @return \Finazon\Grpc\Api\SnapshotLastTrade
     */
    public function getLastTrade()
    {
        return $this->last_trade;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotLastTrade last_trade = 3;</code>
     * @param \Finazon\Grpc\Api\SnapshotLastTrade $var
     * @return $this
     */
    public function setLastTrade($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\SnapshotLastTrade::class);
        $this->last_trade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv previous_day = 4;</code>
     * @return \Finazon\Grpc\Api\SnapshotOhlcv
     */
    public function getPreviousDay()
    {
        return $this->previous_day;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotOhlcv previous_day = 4;</code>
     * @param \Finazon\Grpc\Api\SnapshotOhlcv $var
     * @return $this
     */
    public function setPreviousDay($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\SnapshotOhlcv::class);
        $this->previous_day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotLastFiftyTwoWeek last_fifty_two_week = 5;</code>
     * @return \Finazon\Grpc\Api\SnapshotLastFiftyTwoWeek
     */
    public function getLastFiftyTwoWeek()
    {
        return $this->last_fifty_two_week;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotLastFiftyTwoWeek last_fifty_two_week = 5;</code>
     * @param \Finazon\Grpc\Api\SnapshotLastFiftyTwoWeek $var
     * @return $this
     */
    public function setLastFiftyTwoWeek($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\SnapshotLastFiftyTwoWeek::class);
        $this->last_fifty_two_week = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotChange change = 6;</code>
     * @return \Finazon\Grpc\Api\SnapshotChange
     */
    public function getChange()
    {
        return $this->change;
    }

    /**
     * Generated from protobuf field <code>.finazon.SnapshotChange change = 6;</code>
     * @param \Finazon\Grpc\Api\SnapshotChange $var
     * @return $this
     */
    public function setChange($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\SnapshotChange::class);
        $this->change = $var;

        return $this;
    }

}

