<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sip.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetSipMarketCenterRequest</code>
 */
class GetSipMarketCenterRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Sip::initOnce();
        parent::__construct($data);
    }

}

