<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetTimeSeriesMacdRequest</code>
 */
class GetTimeSeriesMacdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string series_type = 1;</code>
     */
    protected $series_type = '';
    /**
     * Generated from protobuf field <code>int32 fast_period = 2;</code>
     */
    protected $fast_period = 0;
    /**
     * Generated from protobuf field <code>int32 slow_period = 3;</code>
     */
    protected $slow_period = 0;
    /**
     * Generated from protobuf field <code>int32 signal_period = 4;</code>
     */
    protected $signal_period = 0;
    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 5;</code>
     */
    protected $time_series = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $series_type
     *     @type int $fast_period
     *     @type int $slow_period
     *     @type int $signal_period
     *     @type \Finazon\Grpc\Api\GetTimeSeriesRequest $time_series
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\TimeSeries::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string series_type = 1;</code>
     * @return string
     */
    public function getSeriesType()
    {
        return $this->series_type;
    }

    /**
     * Generated from protobuf field <code>string series_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSeriesType($var)
    {
        GPBUtil::checkString($var, True);
        $this->series_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fast_period = 2;</code>
     * @return int
     */
    public function getFastPeriod()
    {
        return $this->fast_period;
    }

    /**
     * Generated from protobuf field <code>int32 fast_period = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFastPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->fast_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 slow_period = 3;</code>
     * @return int
     */
    public function getSlowPeriod()
    {
        return $this->slow_period;
    }

    /**
     * Generated from protobuf field <code>int32 slow_period = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSlowPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->slow_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 signal_period = 4;</code>
     * @return int
     */
    public function getSignalPeriod()
    {
        return $this->signal_period;
    }

    /**
     * Generated from protobuf field <code>int32 signal_period = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSignalPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->signal_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 5;</code>
     * @return \Finazon\Grpc\Api\GetTimeSeriesRequest
     */
    public function getTimeSeries()
    {
        return $this->time_series;
    }

    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 5;</code>
     * @param \Finazon\Grpc\Api\GetTimeSeriesRequest $var
     * @return $this
     */
    public function setTimeSeries($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\GetTimeSeriesRequest::class);
        $this->time_series = $var;

        return $this;
    }

}

