<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\GetTimeSeriesAtrResponse\Atr instead.
     * @deprecated
     */
    class GetTimeSeriesAtrResponse_Atr {}
}
class_exists(GetTimeSeriesAtrResponse\Atr::class);
@trigger_error('Finazon\Grpc\Api\GetTimeSeriesAtrResponse_Atr is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\GetTimeSeriesAtrResponse\Atr instead', E_USER_DEPRECATED);

