<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\GetTimeSeriesIchimokuResponse\Ichimoku instead.
     * @deprecated
     */
    class GetTimeSeriesIchimokuResponse_Ichimoku {}
}
class_exists(GetTimeSeriesIchimokuResponse\Ichimoku::class);
@trigger_error('Finazon\Grpc\Api\GetTimeSeriesIchimokuResponse_Ichimoku is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\GetTimeSeriesIchimokuResponse\Ichimoku instead', E_USER_DEPRECATED);

