<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\GetTimeSeriesRsiResponse\Rsi instead.
     * @deprecated
     */
    class GetTimeSeriesRsiResponse_Rsi {}
}
class_exists(GetTimeSeriesRsiResponse\Rsi::class);
@trigger_error('Finazon\Grpc\Api\GetTimeSeriesRsiResponse_Rsi is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\GetTimeSeriesRsiResponse\Rsi instead', E_USER_DEPRECATED);

