<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\GetTimeSeriesMacdResponse\Macd instead.
     * @deprecated
     */
    class GetTimeSeriesMacdResponse_Macd {}
}
class_exists(GetTimeSeriesMacdResponse\Macd::class);
@trigger_error('Finazon\Grpc\Api\GetTimeSeriesMacdResponse_Macd is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\GetTimeSeriesMacdResponse\Macd instead', E_USER_DEPRECATED);

