<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\GetTimeSeriesStochResponse\Stoch instead.
     * @deprecated
     */
    class GetTimeSeriesStochResponse_Stoch {}
}
class_exists(GetTimeSeriesStochResponse\Stoch::class);
@trigger_error('Finazon\Grpc\Api\GetTimeSeriesStochResponse_Stoch is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\GetTimeSeriesStochResponse\Stoch instead', E_USER_DEPRECATED);

