<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetTimeSeriesIchimokuRequest</code>
 */
class GetTimeSeriesIchimokuRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 conversion_line_period = 1;</code>
     */
    protected $conversion_line_period = 0;
    /**
     * Generated from protobuf field <code>int32 base_line_period = 2;</code>
     */
    protected $base_line_period = 0;
    /**
     * Generated from protobuf field <code>int32 leading_span_b_period = 3;</code>
     */
    protected $leading_span_b_period = 0;
    /**
     * Generated from protobuf field <code>int32 lagging_span_period = 4;</code>
     */
    protected $lagging_span_period = 0;
    /**
     * Generated from protobuf field <code>bool include_ahead_span_period = 5;</code>
     */
    protected $include_ahead_span_period = false;
    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 6;</code>
     */
    protected $time_series = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $conversion_line_period
     *     @type int $base_line_period
     *     @type int $leading_span_b_period
     *     @type int $lagging_span_period
     *     @type bool $include_ahead_span_period
     *     @type \Finazon\Grpc\Api\GetTimeSeriesRequest $time_series
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\TimeSeries::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 conversion_line_period = 1;</code>
     * @return int
     */
    public function getConversionLinePeriod()
    {
        return $this->conversion_line_period;
    }

    /**
     * Generated from protobuf field <code>int32 conversion_line_period = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setConversionLinePeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->conversion_line_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 base_line_period = 2;</code>
     * @return int
     */
    public function getBaseLinePeriod()
    {
        return $this->base_line_period;
    }

    /**
     * Generated from protobuf field <code>int32 base_line_period = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBaseLinePeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->base_line_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 leading_span_b_period = 3;</code>
     * @return int
     */
    public function getLeadingSpanBPeriod()
    {
        return $this->leading_span_b_period;
    }

    /**
     * Generated from protobuf field <code>int32 leading_span_b_period = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLeadingSpanBPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->leading_span_b_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 lagging_span_period = 4;</code>
     * @return int
     */
    public function getLaggingSpanPeriod()
    {
        return $this->lagging_span_period;
    }

    /**
     * Generated from protobuf field <code>int32 lagging_span_period = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLaggingSpanPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->lagging_span_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_ahead_span_period = 5;</code>
     * @return bool
     */
    public function getIncludeAheadSpanPeriod()
    {
        return $this->include_ahead_span_period;
    }

    /**
     * Generated from protobuf field <code>bool include_ahead_span_period = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeAheadSpanPeriod($var)
    {
        GPBUtil::checkBool($var);
        $this->include_ahead_span_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 6;</code>
     * @return \Finazon\Grpc\Api\GetTimeSeriesRequest
     */
    public function getTimeSeries()
    {
        return $this->time_series;
    }

    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 6;</code>
     * @param \Finazon\Grpc\Api\GetTimeSeriesRequest $var
     * @return $this
     */
    public function setTimeSeries($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\GetTimeSeriesRequest::class);
        $this->time_series = $var;

        return $this;
    }

}

