<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetTimeSeriesStochRequest</code>
 */
class GetTimeSeriesStochRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 fast_k_period = 1;</code>
     */
    protected $fast_k_period = 0;
    /**
     * Generated from protobuf field <code>int32 slow_k_period = 2;</code>
     */
    protected $slow_k_period = 0;
    /**
     * Generated from protobuf field <code>int32 slow_d_period = 3;</code>
     */
    protected $slow_d_period = 0;
    /**
     * Generated from protobuf field <code>string slow_kma_type = 4;</code>
     */
    protected $slow_kma_type = '';
    /**
     * Generated from protobuf field <code>string slow_dma_type = 5;</code>
     */
    protected $slow_dma_type = '';
    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 6;</code>
     */
    protected $time_series = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $fast_k_period
     *     @type int $slow_k_period
     *     @type int $slow_d_period
     *     @type string $slow_kma_type
     *     @type string $slow_dma_type
     *     @type \Finazon\Grpc\Api\GetTimeSeriesRequest $time_series
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\TimeSeries::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 fast_k_period = 1;</code>
     * @return int
     */
    public function getFastKPeriod()
    {
        return $this->fast_k_period;
    }

    /**
     * Generated from protobuf field <code>int32 fast_k_period = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFastKPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->fast_k_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 slow_k_period = 2;</code>
     * @return int
     */
    public function getSlowKPeriod()
    {
        return $this->slow_k_period;
    }

    /**
     * Generated from protobuf field <code>int32 slow_k_period = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSlowKPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->slow_k_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 slow_d_period = 3;</code>
     * @return int
     */
    public function getSlowDPeriod()
    {
        return $this->slow_d_period;
    }

    /**
     * Generated from protobuf field <code>int32 slow_d_period = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSlowDPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->slow_d_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string slow_kma_type = 4;</code>
     * @return string
     */
    public function getSlowKmaType()
    {
        return $this->slow_kma_type;
    }

    /**
     * Generated from protobuf field <code>string slow_kma_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSlowKmaType($var)
    {
        GPBUtil::checkString($var, True);
        $this->slow_kma_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string slow_dma_type = 5;</code>
     * @return string
     */
    public function getSlowDmaType()
    {
        return $this->slow_dma_type;
    }

    /**
     * Generated from protobuf field <code>string slow_dma_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSlowDmaType($var)
    {
        GPBUtil::checkString($var, True);
        $this->slow_dma_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 6;</code>
     * @return \Finazon\Grpc\Api\GetTimeSeriesRequest
     */
    public function getTimeSeries()
    {
        return $this->time_series;
    }

    /**
     * Generated from protobuf field <code>.finazon.GetTimeSeriesRequest time_series = 6;</code>
     * @param \Finazon\Grpc\Api\GetTimeSeriesRequest $var
     * @return $this
     */
    public function setTimeSeries($var)
    {
        GPBUtil::checkMessage($var, \Finazon\Grpc\Api\GetTimeSeriesRequest::class);
        $this->time_series = $var;

        return $this;
    }

}

