<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\GetTimeSeriesMaResponse\Ma instead.
     * @deprecated
     */
    class GetTimeSeriesMaResponse_Ma {}
}
class_exists(GetTimeSeriesMaResponse\Ma::class);
@trigger_error('Finazon\Grpc\Api\GetTimeSeriesMaResponse_Ma is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\GetTimeSeriesMaResponse\Ma instead', E_USER_DEPRECATED);

