<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api;

if (false) {
    /**
     * This class is deprecated. Use Finazon\Grpc\Api\GetTimeSeriesBBandsResponse\BBands instead.
     * @deprecated
     */
    class GetTimeSeriesBBandsResponse_BBands {}
}
class_exists(GetTimeSeriesBBandsResponse\BBands::class);
@trigger_error('Finazon\Grpc\Api\GetTimeSeriesBBandsResponse_BBands is deprecated and will be removed in the next major release. Use Finazon\Grpc\Api\GetTimeSeriesBBandsResponse\BBands instead', E_USER_DEPRECATED);

