<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: benzinga.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.IPOItem</code>
 */
class IPOItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string record_id = 1;</code>
     */
    protected $record_id = '';
    /**
     * Generated from protobuf field <code>string ticker = 2;</code>
     */
    protected $ticker = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     */
    protected $mic = '';
    /**
     * Generated from protobuf field <code>string currency = 5;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>string date = 6;</code>
     */
    protected $date = '';
    /**
     * Generated from protobuf field <code>bool open_date_verified = 7;</code>
     */
    protected $open_date_verified = false;
    /**
     * Generated from protobuf field <code>string time = 8;</code>
     */
    protected $time = '';
    /**
     * Generated from protobuf field <code>double price_max = 9;</code>
     */
    protected $price_max = 0.0;
    /**
     * Generated from protobuf field <code>double price_min = 10;</code>
     */
    protected $price_min = 0.0;
    /**
     * Generated from protobuf field <code>double price_open = 11;</code>
     */
    protected $price_open = 0.0;
    /**
     * Generated from protobuf field <code>double price_public_offering = 12;</code>
     */
    protected $price_public_offering = 0.0;
    /**
     * Generated from protobuf field <code>double offering_shares = 13;</code>
     */
    protected $offering_shares = 0.0;
    /**
     * Generated from protobuf field <code>double offering_shares_ord_adr = 14;</code>
     */
    protected $offering_shares_ord_adr = 0.0;
    /**
     * Generated from protobuf field <code>double offering_value = 15;</code>
     */
    protected $offering_value = 0.0;
    /**
     * Generated from protobuf field <code>double ord_shares_out_after_offer = 16;</code>
     */
    protected $ord_shares_out_after_offer = 0.0;
    /**
     * Generated from protobuf field <code>double market_cap_at_offer = 17;</code>
     */
    protected $market_cap_at_offer = 0.0;
    /**
     * Generated from protobuf field <code>string deal_status = 18;</code>
     */
    protected $deal_status = '';
    /**
     * Generated from protobuf field <code>string initial_filing_date = 19;</code>
     */
    protected $initial_filing_date = '';
    /**
     * Generated from protobuf field <code>string insider_lockup_date = 20;</code>
     */
    protected $insider_lockup_date = '';
    /**
     * Generated from protobuf field <code>int32 insider_lockup_days = 21;</code>
     */
    protected $insider_lockup_days = 0;
    /**
     * Generated from protobuf field <code>string ipo_type = 22;</code>
     */
    protected $ipo_type = '';
    /**
     * Generated from protobuf field <code>double last_yr_income = 23;</code>
     */
    protected $last_yr_income = 0.0;
    /**
     * Generated from protobuf field <code>double last_yr_income_year = 24;</code>
     */
    protected $last_yr_income_year = 0.0;
    /**
     * Generated from protobuf field <code>double last_yr_revenue = 25;</code>
     */
    protected $last_yr_revenue = 0.0;
    /**
     * Generated from protobuf field <code>double last_yr_revenue_year = 26;</code>
     */
    protected $last_yr_revenue_year = 0.0;
    /**
     * Generated from protobuf field <code>repeated string lead_underwriters = 27;</code>
     */
    private $lead_underwriters;
    /**
     * Generated from protobuf field <code>repeated string other_underwriters = 28;</code>
     */
    private $other_underwriters;
    /**
     * Generated from protobuf field <code>string notes = 29;</code>
     */
    protected $notes = '';
    /**
     * Generated from protobuf field <code>string pricing_date = 30;</code>
     */
    protected $pricing_date = '';
    /**
     * Generated from protobuf field <code>string sec_accession_number = 31;</code>
     */
    protected $sec_accession_number = '';
    /**
     * Generated from protobuf field <code>string sec_filing_url = 32;</code>
     */
    protected $sec_filing_url = '';
    /**
     * Generated from protobuf field <code>double shares_outstanding = 33;</code>
     */
    protected $shares_outstanding = 0.0;
    /**
     * Generated from protobuf field <code>double sic = 34;</code>
     */
    protected $sic = 0.0;
    /**
     * Generated from protobuf field <code>bool spac_converted_to_target = 35;</code>
     */
    protected $spac_converted_to_target = false;
    /**
     * Generated from protobuf field <code>string state_location = 36;</code>
     */
    protected $state_location = '';
    /**
     * Generated from protobuf field <code>string underwriter_quiet_expiration_date = 37;</code>
     */
    protected $underwriter_quiet_expiration_date = '';
    /**
     * Generated from protobuf field <code>int32 underwriter_quiet_expiration_days = 38;</code>
     */
    protected $underwriter_quiet_expiration_days = 0;
    /**
     * Generated from protobuf field <code>int64 updated = 39;</code>
     */
    protected $updated = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $record_id
     *     @type string $ticker
     *     @type string $name
     *     @type string $mic
     *     @type string $currency
     *     @type string $date
     *     @type bool $open_date_verified
     *     @type string $time
     *     @type float $price_max
     *     @type float $price_min
     *     @type float $price_open
     *     @type float $price_public_offering
     *     @type float $offering_shares
     *     @type float $offering_shares_ord_adr
     *     @type float $offering_value
     *     @type float $ord_shares_out_after_offer
     *     @type float $market_cap_at_offer
     *     @type string $deal_status
     *     @type string $initial_filing_date
     *     @type string $insider_lockup_date
     *     @type int $insider_lockup_days
     *     @type string $ipo_type
     *     @type float $last_yr_income
     *     @type float $last_yr_income_year
     *     @type float $last_yr_revenue
     *     @type float $last_yr_revenue_year
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $lead_underwriters
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $other_underwriters
     *     @type string $notes
     *     @type string $pricing_date
     *     @type string $sec_accession_number
     *     @type string $sec_filing_url
     *     @type float $shares_outstanding
     *     @type float $sic
     *     @type bool $spac_converted_to_target
     *     @type string $state_location
     *     @type string $underwriter_quiet_expiration_date
     *     @type int $underwriter_quiet_expiration_days
     *     @type int|string $updated
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Benzinga::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string record_id = 1;</code>
     * @return string
     */
    public function getRecordId()
    {
        return $this->record_id;
    }

    /**
     * Generated from protobuf field <code>string record_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRecordId($var)
    {
        GPBUtil::checkString($var, True);
        $this->record_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ticker = 2;</code>
     * @return string
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     * Generated from protobuf field <code>string ticker = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTicker($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     * @return string
     */
    public function getMic()
    {
        return $this->mic;
    }

    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMic($var)
    {
        GPBUtil::checkString($var, True);
        $this->mic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 5;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date = 6;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Generated from protobuf field <code>string date = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool open_date_verified = 7;</code>
     * @return bool
     */
    public function getOpenDateVerified()
    {
        return $this->open_date_verified;
    }

    /**
     * Generated from protobuf field <code>bool open_date_verified = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setOpenDateVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->open_date_verified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time = 8;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>string time = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price_max = 9;</code>
     * @return float
     */
    public function getPriceMax()
    {
        return $this->price_max;
    }

    /**
     * Generated from protobuf field <code>double price_max = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setPriceMax($var)
    {
        GPBUtil::checkDouble($var);
        $this->price_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price_min = 10;</code>
     * @return float
     */
    public function getPriceMin()
    {
        return $this->price_min;
    }

    /**
     * Generated from protobuf field <code>double price_min = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setPriceMin($var)
    {
        GPBUtil::checkDouble($var);
        $this->price_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price_open = 11;</code>
     * @return float
     */
    public function getPriceOpen()
    {
        return $this->price_open;
    }

    /**
     * Generated from protobuf field <code>double price_open = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setPriceOpen($var)
    {
        GPBUtil::checkDouble($var);
        $this->price_open = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price_public_offering = 12;</code>
     * @return float
     */
    public function getPricePublicOffering()
    {
        return $this->price_public_offering;
    }

    /**
     * Generated from protobuf field <code>double price_public_offering = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setPricePublicOffering($var)
    {
        GPBUtil::checkDouble($var);
        $this->price_public_offering = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double offering_shares = 13;</code>
     * @return float
     */
    public function getOfferingShares()
    {
        return $this->offering_shares;
    }

    /**
     * Generated from protobuf field <code>double offering_shares = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setOfferingShares($var)
    {
        GPBUtil::checkDouble($var);
        $this->offering_shares = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double offering_shares_ord_adr = 14;</code>
     * @return float
     */
    public function getOfferingSharesOrdAdr()
    {
        return $this->offering_shares_ord_adr;
    }

    /**
     * Generated from protobuf field <code>double offering_shares_ord_adr = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setOfferingSharesOrdAdr($var)
    {
        GPBUtil::checkDouble($var);
        $this->offering_shares_ord_adr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double offering_value = 15;</code>
     * @return float
     */
    public function getOfferingValue()
    {
        return $this->offering_value;
    }

    /**
     * Generated from protobuf field <code>double offering_value = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setOfferingValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->offering_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double ord_shares_out_after_offer = 16;</code>
     * @return float
     */
    public function getOrdSharesOutAfterOffer()
    {
        return $this->ord_shares_out_after_offer;
    }

    /**
     * Generated from protobuf field <code>double ord_shares_out_after_offer = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setOrdSharesOutAfterOffer($var)
    {
        GPBUtil::checkDouble($var);
        $this->ord_shares_out_after_offer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double market_cap_at_offer = 17;</code>
     * @return float
     */
    public function getMarketCapAtOffer()
    {
        return $this->market_cap_at_offer;
    }

    /**
     * Generated from protobuf field <code>double market_cap_at_offer = 17;</code>
     * @param float $var
     * @return $this
     */
    public function setMarketCapAtOffer($var)
    {
        GPBUtil::checkDouble($var);
        $this->market_cap_at_offer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deal_status = 18;</code>
     * @return string
     */
    public function getDealStatus()
    {
        return $this->deal_status;
    }

    /**
     * Generated from protobuf field <code>string deal_status = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setDealStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->deal_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string initial_filing_date = 19;</code>
     * @return string
     */
    public function getInitialFilingDate()
    {
        return $this->initial_filing_date;
    }

    /**
     * Generated from protobuf field <code>string initial_filing_date = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setInitialFilingDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->initial_filing_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string insider_lockup_date = 20;</code>
     * @return string
     */
    public function getInsiderLockupDate()
    {
        return $this->insider_lockup_date;
    }

    /**
     * Generated from protobuf field <code>string insider_lockup_date = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setInsiderLockupDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->insider_lockup_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 insider_lockup_days = 21;</code>
     * @return int
     */
    public function getInsiderLockupDays()
    {
        return $this->insider_lockup_days;
    }

    /**
     * Generated from protobuf field <code>int32 insider_lockup_days = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setInsiderLockupDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->insider_lockup_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ipo_type = 22;</code>
     * @return string
     */
    public function getIpoType()
    {
        return $this->ipo_type;
    }

    /**
     * Generated from protobuf field <code>string ipo_type = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setIpoType($var)
    {
        GPBUtil::checkString($var, True);
        $this->ipo_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double last_yr_income = 23;</code>
     * @return float
     */
    public function getLastYrIncome()
    {
        return $this->last_yr_income;
    }

    /**
     * Generated from protobuf field <code>double last_yr_income = 23;</code>
     * @param float $var
     * @return $this
     */
    public function setLastYrIncome($var)
    {
        GPBUtil::checkDouble($var);
        $this->last_yr_income = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double last_yr_income_year = 24;</code>
     * @return float
     */
    public function getLastYrIncomeYear()
    {
        return $this->last_yr_income_year;
    }

    /**
     * Generated from protobuf field <code>double last_yr_income_year = 24;</code>
     * @param float $var
     * @return $this
     */
    public function setLastYrIncomeYear($var)
    {
        GPBUtil::checkDouble($var);
        $this->last_yr_income_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double last_yr_revenue = 25;</code>
     * @return float
     */
    public function getLastYrRevenue()
    {
        return $this->last_yr_revenue;
    }

    /**
     * Generated from protobuf field <code>double last_yr_revenue = 25;</code>
     * @param float $var
     * @return $this
     */
    public function setLastYrRevenue($var)
    {
        GPBUtil::checkDouble($var);
        $this->last_yr_revenue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double last_yr_revenue_year = 26;</code>
     * @return float
     */
    public function getLastYrRevenueYear()
    {
        return $this->last_yr_revenue_year;
    }

    /**
     * Generated from protobuf field <code>double last_yr_revenue_year = 26;</code>
     * @param float $var
     * @return $this
     */
    public function setLastYrRevenueYear($var)
    {
        GPBUtil::checkDouble($var);
        $this->last_yr_revenue_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string lead_underwriters = 27;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLeadUnderwriters()
    {
        return $this->lead_underwriters;
    }

    /**
     * Generated from protobuf field <code>repeated string lead_underwriters = 27;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLeadUnderwriters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->lead_underwriters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string other_underwriters = 28;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOtherUnderwriters()
    {
        return $this->other_underwriters;
    }

    /**
     * Generated from protobuf field <code>repeated string other_underwriters = 28;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOtherUnderwriters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->other_underwriters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 29;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pricing_date = 30;</code>
     * @return string
     */
    public function getPricingDate()
    {
        return $this->pricing_date;
    }

    /**
     * Generated from protobuf field <code>string pricing_date = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setPricingDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->pricing_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sec_accession_number = 31;</code>
     * @return string
     */
    public function getSecAccessionNumber()
    {
        return $this->sec_accession_number;
    }

    /**
     * Generated from protobuf field <code>string sec_accession_number = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setSecAccessionNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->sec_accession_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sec_filing_url = 32;</code>
     * @return string
     */
    public function getSecFilingUrl()
    {
        return $this->sec_filing_url;
    }

    /**
     * Generated from protobuf field <code>string sec_filing_url = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setSecFilingUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->sec_filing_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double shares_outstanding = 33;</code>
     * @return float
     */
    public function getSharesOutstanding()
    {
        return $this->shares_outstanding;
    }

    /**
     * Generated from protobuf field <code>double shares_outstanding = 33;</code>
     * @param float $var
     * @return $this
     */
    public function setSharesOutstanding($var)
    {
        GPBUtil::checkDouble($var);
        $this->shares_outstanding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double sic = 34;</code>
     * @return float
     */
    public function getSic()
    {
        return $this->sic;
    }

    /**
     * Generated from protobuf field <code>double sic = 34;</code>
     * @param float $var
     * @return $this
     */
    public function setSic($var)
    {
        GPBUtil::checkDouble($var);
        $this->sic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool spac_converted_to_target = 35;</code>
     * @return bool
     */
    public function getSpacConvertedToTarget()
    {
        return $this->spac_converted_to_target;
    }

    /**
     * Generated from protobuf field <code>bool spac_converted_to_target = 35;</code>
     * @param bool $var
     * @return $this
     */
    public function setSpacConvertedToTarget($var)
    {
        GPBUtil::checkBool($var);
        $this->spac_converted_to_target = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string state_location = 36;</code>
     * @return string
     */
    public function getStateLocation()
    {
        return $this->state_location;
    }

    /**
     * Generated from protobuf field <code>string state_location = 36;</code>
     * @param string $var
     * @return $this
     */
    public function setStateLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->state_location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string underwriter_quiet_expiration_date = 37;</code>
     * @return string
     */
    public function getUnderwriterQuietExpirationDate()
    {
        return $this->underwriter_quiet_expiration_date;
    }

    /**
     * Generated from protobuf field <code>string underwriter_quiet_expiration_date = 37;</code>
     * @param string $var
     * @return $this
     */
    public function setUnderwriterQuietExpirationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->underwriter_quiet_expiration_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 underwriter_quiet_expiration_days = 38;</code>
     * @return int
     */
    public function getUnderwriterQuietExpirationDays()
    {
        return $this->underwriter_quiet_expiration_days;
    }

    /**
     * Generated from protobuf field <code>int32 underwriter_quiet_expiration_days = 38;</code>
     * @param int $var
     * @return $this
     */
    public function setUnderwriterQuietExpirationDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->underwriter_quiet_expiration_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated = 39;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Generated from protobuf field <code>int64 updated = 39;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

}

