<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.MarketsStocksResponseItem</code>
 */
class MarketsStocksResponseItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string country = 1;</code>
     */
    protected $country = '';
    /**
     * Generated from protobuf field <code>string mic = 2;</code>
     */
    protected $mic = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $country
     *     @type string $mic
     *     @type string $name
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Exchange::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string country = 1;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mic = 2;</code>
     * @return string
     */
    public function getMic()
    {
        return $this->mic;
    }

    /**
     * Generated from protobuf field <code>string mic = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMic($var)
    {
        GPBUtil::checkString($var, True);
        $this->mic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

