<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sec.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.SecFillingsItem</code>
 */
class SecFillingsItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string ticker = 1;</code>
     */
    private $ticker;
    /**
     * Generated from protobuf field <code>int64 cik = 2;</code>
     */
    protected $cik = 0;
    /**
     * Generated from protobuf field <code>string form_type = 3;</code>
     */
    protected $form_type = '';
    /**
     * Generated from protobuf field <code>int64 filed_at = 4;</code>
     */
    protected $filed_at = 0;
    /**
     * Generated from protobuf field <code>string filing_url = 5;</code>
     */
    protected $filing_url = '';
    /**
     * Generated from protobuf field <code>repeated .finazon.SecFilingFile files = 6;</code>
     */
    private $files;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $ticker
     *     @type int|string $cik
     *     @type string $form_type
     *     @type int|string $filed_at
     *     @type string $filing_url
     *     @type \Finazon\Grpc\Api\SecFilingFile[]|\Google\Protobuf\Internal\RepeatedField $files
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Sec::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string ticker = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     * Generated from protobuf field <code>repeated string ticker = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTicker($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ticker = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 cik = 2;</code>
     * @return int|string
     */
    public function getCik()
    {
        return $this->cik;
    }

    /**
     * Generated from protobuf field <code>int64 cik = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCik($var)
    {
        GPBUtil::checkInt64($var);
        $this->cik = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string form_type = 3;</code>
     * @return string
     */
    public function getFormType()
    {
        return $this->form_type;
    }

    /**
     * Generated from protobuf field <code>string form_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFormType($var)
    {
        GPBUtil::checkString($var, True);
        $this->form_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 filed_at = 4;</code>
     * @return int|string
     */
    public function getFiledAt()
    {
        return $this->filed_at;
    }

    /**
     * Generated from protobuf field <code>int64 filed_at = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFiledAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->filed_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string filing_url = 5;</code>
     * @return string
     */
    public function getFilingUrl()
    {
        return $this->filing_url;
    }

    /**
     * Generated from protobuf field <code>string filing_url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFilingUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->filing_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .finazon.SecFilingFile files = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Generated from protobuf field <code>repeated .finazon.SecFilingFile files = 6;</code>
     * @param \Finazon\Grpc\Api\SecFilingFile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Finazon\Grpc\Api\SecFilingFile::class);
        $this->files = $arr;

        return $this;
    }

}

