<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sip.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.SipTradesItem</code>
 */
class SipTradesItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 trade_date = 1;</code>
     */
    protected $trade_date = 0;
    /**
     * Generated from protobuf field <code>string market_center = 2;</code>
     */
    protected $market_center = '';
    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     */
    protected $topic = '';
    /**
     * Generated from protobuf field <code>double price = 4;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>int64 quantity = 5;</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>string sales_conditions = 6;</code>
     */
    protected $sales_conditions = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $trade_date
     *     @type string $market_center
     *     @type string $topic
     *     @type float $price
     *     @type int|string $quantity
     *     @type string $sales_conditions
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Sip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 trade_date = 1;</code>
     * @return int|string
     */
    public function getTradeDate()
    {
        return $this->trade_date;
    }

    /**
     * Generated from protobuf field <code>int64 trade_date = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTradeDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->trade_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string market_center = 2;</code>
     * @return string
     */
    public function getMarketCenter()
    {
        return $this->market_center;
    }

    /**
     * Generated from protobuf field <code>string market_center = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMarketCenter($var)
    {
        GPBUtil::checkString($var, True);
        $this->market_center = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 4;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 quantity = 5;</code>
     * @return int|string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int64 quantity = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sales_conditions = 6;</code>
     * @return string
     */
    public function getSalesConditions()
    {
        return $this->sales_conditions;
    }

    /**
     * Generated from protobuf field <code>string sales_conditions = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSalesConditions($var)
    {
        GPBUtil::checkString($var, True);
        $this->sales_conditions = $var;

        return $this;
    }

}

