<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.SnapshotOhlcv</code>
 */
class SnapshotOhlcv extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double open = 1;</code>
     */
    protected $open = 0.0;
    /**
     * Generated from protobuf field <code>double high = 2;</code>
     */
    protected $high = 0.0;
    /**
     * Generated from protobuf field <code>double low = 3;</code>
     */
    protected $low = 0.0;
    /**
     * Generated from protobuf field <code>double close = 4;</code>
     */
    protected $close = 0.0;
    /**
     * Generated from protobuf field <code>double volume = 5;</code>
     */
    protected $volume = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $open
     *     @type float $high
     *     @type float $low
     *     @type float $close
     *     @type float $volume
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Snapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double open = 1;</code>
     * @return float
     */
    public function getOpen()
    {
        return $this->open;
    }

    /**
     * Generated from protobuf field <code>double open = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setOpen($var)
    {
        GPBUtil::checkDouble($var);
        $this->open = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double high = 2;</code>
     * @return float
     */
    public function getHigh()
    {
        return $this->high;
    }

    /**
     * Generated from protobuf field <code>double high = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setHigh($var)
    {
        GPBUtil::checkDouble($var);
        $this->high = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double low = 3;</code>
     * @return float
     */
    public function getLow()
    {
        return $this->low;
    }

    /**
     * Generated from protobuf field <code>double low = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLow($var)
    {
        GPBUtil::checkDouble($var);
        $this->low = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double close = 4;</code>
     * @return float
     */
    public function getClose()
    {
        return $this->close;
    }

    /**
     * Generated from protobuf field <code>double close = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setClose($var)
    {
        GPBUtil::checkDouble($var);
        $this->close = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double volume = 5;</code>
     * @return float
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>double volume = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkDouble($var);
        $this->volume = $var;

        return $this;
    }

}

