<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.SnapshotChange</code>
 */
class SnapshotChange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double day_change_percent = 1;</code>
     */
    protected $day_change_percent = 0.0;
    /**
     * Generated from protobuf field <code>double week_change_percent = 2;</code>
     */
    protected $week_change_percent = 0.0;
    /**
     * Generated from protobuf field <code>double month_change_percent = 3;</code>
     */
    protected $month_change_percent = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $day_change_percent
     *     @type float $week_change_percent
     *     @type float $month_change_percent
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Snapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double day_change_percent = 1;</code>
     * @return float
     */
    public function getDayChangePercent()
    {
        return $this->day_change_percent;
    }

    /**
     * Generated from protobuf field <code>double day_change_percent = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDayChangePercent($var)
    {
        GPBUtil::checkDouble($var);
        $this->day_change_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double week_change_percent = 2;</code>
     * @return float
     */
    public function getWeekChangePercent()
    {
        return $this->week_change_percent;
    }

    /**
     * Generated from protobuf field <code>double week_change_percent = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setWeekChangePercent($var)
    {
        GPBUtil::checkDouble($var);
        $this->week_change_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double month_change_percent = 3;</code>
     * @return float
     */
    public function getMonthChangePercent()
    {
        return $this->month_change_percent;
    }

    /**
     * Generated from protobuf field <code>double month_change_percent = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMonthChangePercent($var)
    {
        GPBUtil::checkDouble($var);
        $this->month_change_percent = $var;

        return $this;
    }

}

