<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tickers.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.TickerStocksInfo</code>
 */
class TickerStocksInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     */
    protected $ticker = '';
    /**
     * Generated from protobuf field <code>string country = 2;</code>
     */
    protected $country = '';
    /**
     * Generated from protobuf field <code>string currency = 3;</code>
     */
    protected $currency = '';
    /**
     * string mic = 4;
     *
     * Generated from protobuf field <code>string publisher = 4;</code>
     */
    protected $publisher = '';
    /**
     * Generated from protobuf field <code>string publisher_name = 5;</code>
     */
    protected $publisher_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ticker
     *     @type string $country
     *     @type string $currency
     *     @type string $publisher
     *           string mic = 4;
     *     @type string $publisher_name
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Tickers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     * @return string
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTicker($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 2;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 3;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * string mic = 4;
     *
     * Generated from protobuf field <code>string publisher = 4;</code>
     * @return string
     */
    public function getPublisher()
    {
        return $this->publisher;
    }

    /**
     * string mic = 4;
     *
     * Generated from protobuf field <code>string publisher = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisher($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string publisher_name = 5;</code>
     * @return string
     */
    public function getPublisherName()
    {
        return $this->publisher_name;
    }

    /**
     * Generated from protobuf field <code>string publisher_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherName($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher_name = $var;

        return $this;
    }

}

