<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tickers.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *US tickers
 *
 * Generated from protobuf message <code>finazon.TickerUSInfo</code>
 */
class TickerUSInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     */
    protected $ticker = '';
    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>string security = 3;</code>
     */
    protected $security = '';
    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     */
    protected $mic = '';
    /**
     * Generated from protobuf field <code>string asset_type = 5;</code>
     */
    protected $asset_type = '';
    /**
     * Generated from protobuf field <code>string cik = 7;</code>
     */
    protected $cik = '';
    /**
     * Generated from protobuf field <code>string composite_figi = 10;</code>
     */
    protected $composite_figi = '';
    /**
     * Generated from protobuf field <code>string share_figi = 11;</code>
     */
    protected $share_figi = '';
    /**
     * Generated from protobuf field <code>string lei = 12;</code>
     */
    protected $lei = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ticker
     *     @type string $currency
     *     @type string $security
     *     @type string $mic
     *     @type string $asset_type
     *     @type string $cik
     *     @type string $composite_figi
     *     @type string $share_figi
     *     @type string $lei
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Tickers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     * @return string
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     * Generated from protobuf field <code>string ticker = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTicker($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string security = 3;</code>
     * @return string
     */
    public function getSecurity()
    {
        return $this->security;
    }

    /**
     * Generated from protobuf field <code>string security = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSecurity($var)
    {
        GPBUtil::checkString($var, True);
        $this->security = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     * @return string
     */
    public function getMic()
    {
        return $this->mic;
    }

    /**
     * Generated from protobuf field <code>string mic = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMic($var)
    {
        GPBUtil::checkString($var, True);
        $this->mic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string asset_type = 5;</code>
     * @return string
     */
    public function getAssetType()
    {
        return $this->asset_type;
    }

    /**
     * Generated from protobuf field <code>string asset_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAssetType($var)
    {
        GPBUtil::checkString($var, True);
        $this->asset_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cik = 7;</code>
     * @return string
     */
    public function getCik()
    {
        return $this->cik;
    }

    /**
     * Generated from protobuf field <code>string cik = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCik($var)
    {
        GPBUtil::checkString($var, True);
        $this->cik = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string composite_figi = 10;</code>
     * @return string
     */
    public function getCompositeFigi()
    {
        return $this->composite_figi;
    }

    /**
     * Generated from protobuf field <code>string composite_figi = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCompositeFigi($var)
    {
        GPBUtil::checkString($var, True);
        $this->composite_figi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string share_figi = 11;</code>
     * @return string
     */
    public function getShareFigi()
    {
        return $this->share_figi;
    }

    /**
     * Generated from protobuf field <code>string share_figi = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setShareFigi($var)
    {
        GPBUtil::checkString($var, True);
        $this->share_figi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lei = 12;</code>
     * @return string
     */
    public function getLei()
    {
        return $this->lei;
    }

    /**
     * Generated from protobuf field <code>string lei = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setLei($var)
    {
        GPBUtil::checkString($var, True);
        $this->lei = $var;

        return $this;
    }

}

