<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Finazon\Grpc\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.TradesItem</code>
 */
class TradesItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 trade_date = 1;</code>
     */
    protected $trade_date = 0;
    /**
     * Generated from protobuf field <code>double price = 2;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>int64 quantity = 3;</code>
     */
    protected $quantity = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $trade_date
     *     @type float $price
     *     @type int|string $quantity
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Trade::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 trade_date = 1;</code>
     * @return int|string
     */
    public function getTradeDate()
    {
        return $this->trade_date;
    }

    /**
     * Generated from protobuf field <code>int64 trade_date = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTradeDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->trade_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 2;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 quantity = 3;</code>
     * @return int|string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int64 quantity = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->quantity = $var;

        return $this;
    }

}

