<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: benzinga.proto

namespace Finazon\Grpc\Api\EarningsCalendarItem;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.EarningsCalendarItem.Eps</code>
 */
class Eps extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double estimated = 1;</code>
     */
    protected $estimated = 0.0;
    /**
     * Generated from protobuf field <code>double prior = 2;</code>
     */
    protected $prior = 0.0;
    /**
     * Generated from protobuf field <code>double reported = 3;</code>
     */
    protected $reported = 0.0;
    /**
     * Generated from protobuf field <code>double surprise = 4;</code>
     */
    protected $surprise = 0.0;
    /**
     * Generated from protobuf field <code>double surprise_percent = 5;</code>
     */
    protected $surprise_percent = 0.0;
    /**
     * Generated from protobuf field <code>string type = 6;</code>
     */
    protected $type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $estimated
     *     @type float $prior
     *     @type float $reported
     *     @type float $surprise
     *     @type float $surprise_percent
     *     @type string $type
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\Benzinga::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double estimated = 1;</code>
     * @return float
     */
    public function getEstimated()
    {
        return $this->estimated;
    }

    /**
     * Generated from protobuf field <code>double estimated = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setEstimated($var)
    {
        GPBUtil::checkDouble($var);
        $this->estimated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double prior = 2;</code>
     * @return float
     */
    public function getPrior()
    {
        return $this->prior;
    }

    /**
     * Generated from protobuf field <code>double prior = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setPrior($var)
    {
        GPBUtil::checkDouble($var);
        $this->prior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double reported = 3;</code>
     * @return float
     */
    public function getReported()
    {
        return $this->reported;
    }

    /**
     * Generated from protobuf field <code>double reported = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setReported($var)
    {
        GPBUtil::checkDouble($var);
        $this->reported = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double surprise = 4;</code>
     * @return float
     */
    public function getSurprise()
    {
        return $this->surprise;
    }

    /**
     * Generated from protobuf field <code>double surprise = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setSurprise($var)
    {
        GPBUtil::checkDouble($var);
        $this->surprise = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double surprise_percent = 5;</code>
     * @return float
     */
    public function getSurprisePercent()
    {
        return $this->surprise_percent;
    }

    /**
     * Generated from protobuf field <code>double surprise_percent = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setSurprisePercent($var)
    {
        GPBUtil::checkDouble($var);
        $this->surprise_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 6;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Eps::class, \Finazon\Grpc\Api\EarningsCalendarItem_Eps::class);

