<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api\GetTimeSeriesStochResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetTimeSeriesStochResponse.Stoch</code>
 */
class Stoch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>string slow_k = 2;</code>
     */
    protected $slow_k = '';
    /**
     * Generated from protobuf field <code>string slow_d = 3;</code>
     */
    protected $slow_d = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *     @type string $slow_k
     *     @type string $slow_d
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\TimeSeries::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string slow_k = 2;</code>
     * @return string
     */
    public function getSlowK()
    {
        return $this->slow_k;
    }

    /**
     * Generated from protobuf field <code>string slow_k = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSlowK($var)
    {
        GPBUtil::checkString($var, True);
        $this->slow_k = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string slow_d = 3;</code>
     * @return string
     */
    public function getSlowD()
    {
        return $this->slow_d;
    }

    /**
     * Generated from protobuf field <code>string slow_d = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSlowD($var)
    {
        GPBUtil::checkString($var, True);
        $this->slow_d = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Stoch::class, \Finazon\Grpc\Api\GetTimeSeriesStochResponse_Stoch::class);

