<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api\GetTimeSeriesBBandsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetTimeSeriesBBandsResponse.BBands</code>
 */
class BBands extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>string upper_band = 2;</code>
     */
    protected $upper_band = '';
    /**
     * Generated from protobuf field <code>string middle_band = 3;</code>
     */
    protected $middle_band = '';
    /**
     * Generated from protobuf field <code>string lower_band = 4;</code>
     */
    protected $lower_band = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *     @type string $upper_band
     *     @type string $middle_band
     *     @type string $lower_band
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\TimeSeries::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string upper_band = 2;</code>
     * @return string
     */
    public function getUpperBand()
    {
        return $this->upper_band;
    }

    /**
     * Generated from protobuf field <code>string upper_band = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUpperBand($var)
    {
        GPBUtil::checkString($var, True);
        $this->upper_band = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string middle_band = 3;</code>
     * @return string
     */
    public function getMiddleBand()
    {
        return $this->middle_band;
    }

    /**
     * Generated from protobuf field <code>string middle_band = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMiddleBand($var)
    {
        GPBUtil::checkString($var, True);
        $this->middle_band = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lower_band = 4;</code>
     * @return string
     */
    public function getLowerBand()
    {
        return $this->lower_band;
    }

    /**
     * Generated from protobuf field <code>string lower_band = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLowerBand($var)
    {
        GPBUtil::checkString($var, True);
        $this->lower_band = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(BBands::class, \Finazon\Grpc\Api\GetTimeSeriesBBandsResponse_BBands::class);

