<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_series.proto

namespace Finazon\Grpc\Api\GetTimeSeriesIchimokuResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finazon.GetTimeSeriesIchimokuResponse.Ichimoku</code>
 */
class Ichimoku extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>string tenkan_sen = 2;</code>
     */
    protected $tenkan_sen = '';
    /**
     * Generated from protobuf field <code>string kijun_sen = 3;</code>
     */
    protected $kijun_sen = '';
    /**
     * Generated from protobuf field <code>string senkou_span_a = 4;</code>
     */
    protected $senkou_span_a = '';
    /**
     * Generated from protobuf field <code>string senkou_span_b = 5;</code>
     */
    protected $senkou_span_b = '';
    /**
     * Generated from protobuf field <code>string chikou_span = 6;</code>
     */
    protected $chikou_span = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *     @type string $tenkan_sen
     *     @type string $kijun_sen
     *     @type string $senkou_span_a
     *     @type string $senkou_span_b
     *     @type string $chikou_span
     * }
     */
    public function __construct($data = NULL) {
        \Finazon\Grpc\GPBMetadata\TimeSeries::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tenkan_sen = 2;</code>
     * @return string
     */
    public function getTenkanSen()
    {
        return $this->tenkan_sen;
    }

    /**
     * Generated from protobuf field <code>string tenkan_sen = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTenkanSen($var)
    {
        GPBUtil::checkString($var, True);
        $this->tenkan_sen = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kijun_sen = 3;</code>
     * @return string
     */
    public function getKijunSen()
    {
        return $this->kijun_sen;
    }

    /**
     * Generated from protobuf field <code>string kijun_sen = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKijunSen($var)
    {
        GPBUtil::checkString($var, True);
        $this->kijun_sen = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string senkou_span_a = 4;</code>
     * @return string
     */
    public function getSenkouSpanA()
    {
        return $this->senkou_span_a;
    }

    /**
     * Generated from protobuf field <code>string senkou_span_a = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSenkouSpanA($var)
    {
        GPBUtil::checkString($var, True);
        $this->senkou_span_a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string senkou_span_b = 5;</code>
     * @return string
     */
    public function getSenkouSpanB()
    {
        return $this->senkou_span_b;
    }

    /**
     * Generated from protobuf field <code>string senkou_span_b = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSenkouSpanB($var)
    {
        GPBUtil::checkString($var, True);
        $this->senkou_span_b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chikou_span = 6;</code>
     * @return string
     */
    public function getChikouSpan()
    {
        return $this->chikou_span;
    }

    /**
     * Generated from protobuf field <code>string chikou_span = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setChikouSpan($var)
    {
        GPBUtil::checkString($var, True);
        $this->chikou_span = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Ichimoku::class, \Finazon\Grpc\Api\GetTimeSeriesIchimokuResponse_Ichimoku::class);

